#!/bin/bash +x
cat $1 | ./zd_combine.py -n user -c ip -c useragent | ./zd_cut.py -f user -f page | ./zd_sort.py -f user -f page | ./drop_first.py | uniq | cut -f 1 > tempBounceRateFile
cat tempBounceRateFile | wc -l > totalLogLines
cat tempBounceRateFile | uniq -c | sort > bounceLines
./bounce_rate_calc.py totalLogLines bounceLines
echo ""

