#!/bin/bash
echo "slowest $1 pages (server_ms):"
./zd_cut.py -f page -f server_ms | ./zd_sort.py -f page -f server_ms -n 2 | ./zd_select.py "d['server_ms'] != '-'" | ./zd_stat.py -a ave_serverms -g page -d server_ms | ./zd_cut.py -f page -f ave_serverms | ./zd_sort.py -f ave_serverms -g -r | ./drop_first.py | uniq | tail -n $1
echo ""
