#!/bin/bash
echo "slowest $1 pages (server_ms + loadtime):"
./zd_cut.py -f page -f server_ms -f loadtime | ./zd_add.py -n server_load_sum -a server_ms -a loadtime | ./zd_sort.py -f page -f server_load_sum -n 1 | ./zd_stat.py -a ave -g page -d server_load_sum | ./zd_sort.py -f ave -g -r | ./zd_cut.py -f page -f ave | ./drop_first.py | uniq | tail -n $1
echo ""

