#!/bin/bash
echo "top $2 $1s:<br>"
./zd_sort.py -f $1 | ./zd_stat.py -c count | ./zd_cut.py -f $1 -f count > /var/tmp/tempTopFieldOutput
cat /var/tmp/tempTopFieldOutput | wc -l > /var/tmp/totalLogLines
cat /var/tmp/tempTopFieldOutput | uniq -c | ./zd_sort.py -nr | head -n $2 > /var/tmp/tempTopFieldOutput2
./top_field_calc.py /var/tmp/totalLogLines /var/tmp/tempTopFieldOutput2 | ./flat_to_html.py
echo "<br><br>"
