#!/bin/bash
echo "top $2 $1s:"
./zd_cut.py -f $1 > tempTopFieldCutOutput
cat tempTopFieldCutOutput | ./drop_first.py | wc -l > totalLogLines
cat tempTopFieldCutOutput | ./zd_select.py "$3" | ./drop_first.py | sort > tempTopFieldSelectOutput
cat tempTopFieldSelectOutput | uniq -c | sort -nr | head -n $2 > tempTopFieldOutput2
./top_field_calc.py totalLogLines tempTopFieldOutput2
echo ""
