#!/bin/bash
echo "top $3 $2s:"
cat $1 | python zd_cut.py -f $2 | python drop_first.py | sort > tempTopFieldOutput
cat tempTopFieldOutput | wc -l > totalLogLines
cat tempTopFieldOutput | uniq -c | sort -nr | head -n $3 > tempTopFieldOutput2
./top_field_calc.py totalLogLines tempTopFieldOutput2
echo ""
